# Makefile for PA controller application

# 交叉编译工具链 bin 目录；Ubuntu 编译时通常指向厂家 SDK 内的 aarch64 gcc。
TOOLCHAIN_DIR ?= /home/zhe/sdk/kosmo2/pango_config/misc/toolchain/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu/bin
# 交叉编译工具前缀；CC/STRIP 默认由它拼出。
CROSS_COMPILE ?= $(TOOLCHAIN_DIR)/aarch64-linux-gnu-
ifeq ($(origin CC),default)
# C 编译器；如 CLion/命令行显式传 CC，则优先使用外部传入值。
CC = $(CROSS_COMPILE)gcc
endif
# strip 工具；deploy 目标用它生成去符号版本。
STRIP ?= $(CROSS_COMPILE)strip

# 输出目标与构建目录。
TARGET = pa_controller
BUILD_DIR = build
BIN_DIR = $(BUILD_DIR)/bin

# 本应用软件版本号，启动日志和 VERSION 命令会显示。
APP_VERSION ?= 0.1.0
# 本次构建时间，启动日志和 VERSION 命令会显示。
BUILD_TIME ?= $(shell date '+%Y-%m-%d %H:%M:%S %z')

# 启动后是否自动进入工作模式。默认 0，便于寄存器级调试 dynamic/GIC/IMG_WR。
WORK_MODE_AUTO_START ?= 0
# 默认启动的工作模式编号。当前实现 0=Idle/Static Idle、7=Continuous/Dynamic。
WORK_MODE_DEFAULT_MODE ?= 0

# 开发板部署/运行参数，deploy-board 和 run-board 目标使用。
# 部署目标板 IP。
BOARD_HOST ?= 192.168.3.54
# 部署目标板用户名。
BOARD_USER ?= root
# 部署目标板密码；仅 deploy-board/run-board 调试使用。
BOARD_PASS ?= root
# 程序复制到目标板后的目录。
BOARD_DIR ?= /root
# run-board 远程启动参数；默认走 RS422 串口模式。
BOARD_RUN_ARGS ?= -d $(RS422_DEVICE) -b $(RS422_BAUD)
# 非交互 ssh/scp 密码工具；如果已经免密，也可以在命令行覆盖为空或自定义。
SSHPASS ?= sshpass -p $(BOARD_PASS)

# 编译架构和 PA/PU AXI-lite 寄存器访问入口。
# ARMv8-A 目标架构，传给 gcc -march。
ARCH ?= armv8-a
# PA/PU AXI-lite 寄存器物理基地址；当前寄存器不走 UIO 时由 /dev/mem 使用。
PA_PU_BASE_ADDR ?= 0x40000000
# PA/PU 寄存器 UIO 节点；留空表示使用 /dev/mem + PA_PU_BASE_ADDR。
PA_PU_UIO_DEVICE ?=

# 上位机通讯串口配置。
# RS422 设备节点。
RS422_DEVICE ?= /dev/ttyS1
# RS422 波特率。
RS422_BAUD ?= 115200

# FPGA 写入 DDR 的整幅图尺寸，以及应用实际处理的有效图像尺寸。
# FPGA/DDR 中整幅图列数。
DEVICE_WIDTH ?= 3072
# FPGA/DDR 中整幅图行数。
DEVICE_HEIGHT ?= 7680
# 应用实际参与统计、模板和输出的有效图像列数。
IMAGE_WIDTH ?= 3072
# 应用实际参与统计、模板和输出的有效图像行数。
IMAGE_HEIGHT ?= 7680

# 有效图像在整幅 FPGA 图像中的起始偏移。
# 有效图像起始列偏移。
COL_OFFSET ?= 0
# 有效图像起始行偏移。
ROW_OFFSET ?= 0

# 三块共享 DDR 对应的 UIO 设备节点。
# offset/暗场模板 DDR 对应的 UIO 节点。
FPGA_OFFSET_UIO_DEVICE ?= /dev/uio0
# gain/亮场模板 DDR 对应的 UIO 节点。
FPGA_GAIN_UIO_DEVICE ?= /dev/uio1
# 实际输出图环形池 DDR 对应的 UIO 节点。
FPGA_IMAGE_UIO_DEVICE ?= /dev/uio2

# 共享 DDR 的物理地址和 UIO 窗口大小由设备树 UIO map0 提供：
#   /sys/class/uio/uioX/maps/map0/addr
#   /sys/class/uio/uioX/maps/map0/size
# 应用启动时自动读取，不再在 Makefile 中重复维护。
# 输出图环形池单帧首地址/步进对齐；IMG_WR 地址协议至少要求 1KB 对齐。
DDR_IMAGE_FRAME_ALIGN ?= 4096
# Static Idle 输出图环形池最大帧数；实际不能超过 /dev/uio2 map0/size 可容纳的帧数，目前运行的最大张数是9。
DDR_IMAGE_POOL_FRAME_COUNT ?= 9
# UIO 打开失败时是否允许回退 /dev/mem，默认关闭。
FPGA_MEM_USE_DEVMEM_FALLBACK ?= 0

# CONFIG_CORR 不带参数时使用的图像校正默认配置。
# img_pkg_num = 行 * 列 * 2 / 1024，默认 7680x3072x16bit 图像为 46080 包。
# 默认校正图像行数，写入 IMG_ROW_NUM。
CORR_DEFAULT_ROW_NUM ?= 7680
# 默认校正图像列数，写入 IMG_COL_NUM。
CORR_DEFAULT_COL_NUM ?= 3072
# 默认图像包数量，写入 IMG_PKG_NUM。
CORR_DEFAULT_PKG_NUM ?= $(shell expr $(CORR_DEFAULT_ROW_NUM) \* $(CORR_DEFAULT_COL_NUM) \* 2 / 1024)
# 默认是否启用 offset 校正，写入 IMG_CORR_OFFSET_EN。
CORR_DEFAULT_OFFSET_EN ?= 1
# 默认 offset 校正附加值，写入 IMG_CORR_OFFSET_ADDER_VALUE。
CORR_DEFAULT_OFFSET_ADDER_VALUE ?= 100
# 默认 offset 校正模式，写入 IMG_OFFSET_CORR_MODE；0=静态 offset，1=动态 offset。
CORR_DEFAULT_OFFSET_CORR_MODE ?= 0
# 默认是否启用 gain 校正，写入 IMG_CORR_GAIN_EN。
CORR_DEFAULT_GAIN_EN ?= 1
# 默认 gain 限幅值，写入 IMG_CORR_GAIN_CLIPPING_VALUE。
CORR_DEFAULT_GAIN_CLIPPING_VALUE ?= 55000
# 默认是否启用 defect 校正；当前 defect 通过 gain=0 标记。
CORR_DEFAULT_DEFECT_EN ?= 1

# IMG_UPLOAD 模板上传默认配置。
# 无 UIO 上下文时的备用地址；正常运行默认使用 uio0 offset 模板物理基地址。
IMG_UPLOAD_DEFAULT_ADDR ?= 0
# 默认上传图片行数。
IMG_UPLOAD_DEFAULT_ROW_NUM ?= $(IMAGE_HEIGHT)
# 默认上传图片列数。
IMG_UPLOAD_DEFAULT_COL_NUM ?= $(IMAGE_WIDTH)
# 默认上传分包数量，按 row * col * 2 / 1024 计算。
IMG_UPLOAD_DEFAULT_PKG_NUM ?= $(shell expr $(IMG_UPLOAD_DEFAULT_ROW_NUM) \* $(IMG_UPLOAD_DEFAULT_COL_NUM) \* 2 / 1024)

# START_GIC/START_ROIC/START_CORR/SEND_SINGLE 等命令等待中断的参数。
# 等待目标中断 bit 的总超时时间，单位 ms。
PA_PU_IRQ_TIMEOUT_MS ?= 10000
# 没有加载 /dev/pa_irq 驱动时，程序回退到轮询 INT_VECTOR 的间隔，单位 us。
PA_PU_IRQ_POLL_INTERVAL_US ?= 10000
# 无 /dev/pa_irq 回退轮询时是否用忙等代替 usleep；1=忙等，0=usleep。
PA_PU_IRQ_POLL_BUSY_WAIT ?= 0
# 忙等模式下每次轮询之间执行的空循环次数；只在 PA_PU_IRQ_POLL_BUSY_WAIT=1 时生效。
PA_PU_IRQ_POLL_BUSY_SPINS ?= 20000
# 是否打印每次收到的 INT_VECTOR/F2P 中断，用于临时确认设备确实在运行。
# 连续模式下会逐帧触发中断，正常构建默认关闭，避免 START_CONTINUOUS 后刷屏。
PA_PU_IRQ_EVENT_LOG_ENABLE ?= 0
# PA/PU F2P 中断驱动节点；存在时优先用驱动阻塞等待，不存在时回退 INT_VECTOR 轮询。
PA_IRQ_DEVICE ?= /dev/pa_irq

# Continuous/Dynamic 由 FPGA 根据 cycle/地址范围/step 表自主运行。
DYNAMIC_CYCLE_NUM ?= 10
DYNAMIC_IMG_START_ADDR ?= 0x26A00000
DYNAMIC_IMG_END_ADDR ?= 0x3FFFFFFF
# step0：enable=1、req_code=0(idle)、time=50ms。
DYNAMIC_STEP_0_CFG_H ?= 0x80000000
DYNAMIC_STEP_0_CFG_L ?= 50
# step1：enable=1、req_code=4(capture one image)、time=50ms。
DYNAMIC_STEP_1_CFG_H ?= 0x80000004
DYNAMIC_STEP_1_CFG_L ?= 50
# step2~step9 默认关闭；需要组合清空、等待同步等流程时分别覆盖 high/low。
DYNAMIC_STEP_2_CFG_H ?= 0
DYNAMIC_STEP_2_CFG_L ?= 0
DYNAMIC_STEP_3_CFG_H ?= 0
DYNAMIC_STEP_3_CFG_L ?= 0
DYNAMIC_STEP_4_CFG_H ?= 0
DYNAMIC_STEP_4_CFG_L ?= 0
DYNAMIC_STEP_5_CFG_H ?= 0
DYNAMIC_STEP_5_CFG_L ?= 0
DYNAMIC_STEP_6_CFG_H ?= 0
DYNAMIC_STEP_6_CFG_L ?= 0
DYNAMIC_STEP_7_CFG_H ?= 0
DYNAMIC_STEP_7_CFG_L ?= 0
DYNAMIC_STEP_8_CFG_H ?= 0
DYNAMIC_STEP_8_CFG_L ?= 0
DYNAMIC_STEP_9_CFG_H ?= 0
DYNAMIC_STEP_9_CFG_L ?= 0
# 写 DYNC_STR 后等待 DYNC_STATE busy 置位的最长时间。
DYNAMIC_START_TIMEOUT_MS ?= 1000
# ARM 只轮询非 read-clear 的 DYNC_STATE/END/DEBUG，间隔单位 ms。
DYNAMIC_STATE_POLL_INTERVAL_MS ?= 10
# 写 DYNC_STOP 后等待 FPGA dynamic state 释放的最长时间。
DYNAMIC_STOP_TIMEOUT_MS ?= 2000

# Static Idle 工作模式默认时间窗口，单位 ms。
# 空闲自清空间隔时间，单位 ms。
STATIC_IDLE_CLEAN_INTERVAL_MS ?= 50
# 收到采图请求后进入亮场采集前的曝光窗口时间，单位 ms。
STATIC_IDLE_EXPOSURE_MS ?= 50
# 亮场采集完成后进入暗场采集前的窗口时间，单位 ms。
STATIC_IDLE_DARK_WINDOW_MS ?= 50
# Static Idle 自清空正常流程日志开关。0 只打印错误；1 打印 start/wait/done。
STATIC_IDLE_CLEAN_LOG_ENABLE ?= 0

# 模板和校准中间文件路径。
# offset 模板落盘文件；MAKE_OFFSET/MAKE_DYNC_OFFSET 成功后写入，启动时 LOAD_TEMPLATE 会读取。
TEMPLATE_OFFSET_FILE ?= /usr/local/offset.raw
# gain 模板落盘文件；MAKE_GAIN/CAL_GAIN_BUILD 成功后写入，启动时 LOAD_TEMPLATE 会读取。
TEMPLATE_GAIN_FILE ?= /usr/local/gain.raw
# gain/defect 多灰阶校准的均值图中间文件目录。
CAL_GAIN_DIR ?= /usr/local/calib
# Gain 模板任务执行方式：0=前台同步，1=后台异步。
# 控制 CAL_GAIN_CAPTURE、CAL_GAIN_BUILD 和 MAKE_GAIN；Dynamic offset 不受影响。
GAIN_TASK_BACKGROUND_ENABLE ?= 0

# CONFIG_GIC 不带参数时使用的 GIC 时序和行范围默认配置。
# 默认 GIC 请求码；0=serial scan。
GIC_DEFAULT_REQ_CODE ?= 0
# 默认 GIC 是否输出数据；1=输出，0=只清空/不输出。
GIC_DEFAULT_DOUT_EN ?= 1
# 默认 GIC 行时间，单位 ns。
GIC_DEFAULT_LINE_TIME_NS ?= 25600
# 默认 OE 上升沿位置，单位 ns。
GIC_DEFAULT_OE_RISE_NS ?= 0
# 默认 OE 下降沿位置，单位 ns。
GIC_DEFAULT_OE_FALL_NS ?= 0
# 默认起始行。
GIC_DEFAULT_START_ROW ?= 0
# 默认结束行；默认等于有效图像最后一行。
GIC_DEFAULT_END_ROW ?= $(shell expr $(IMAGE_HEIGHT) - 1)
# 默认 GIC binning 模式。
GIC_DEFAULT_BINNING ?= 0

# CONFIG_ROIC 不带参数时使用的列范围和 binning 默认配置。
# 默认 ROIC 起始列。
ROIC_DEFAULT_START_COL ?= 0
# 默认 ROIC 结束列；默认等于有效图像最后一列。
ROIC_DEFAULT_END_COL ?= $(shell expr $(IMAGE_WIDTH) - 1)

# 默认 ROIC binning 模式；当前新寄存器表默认 0。
ROIC_DEFAULT_BINNING ?= 0

# CONFIG_ROIC 下发的 ROIC 芯片寄存器默认值，当前为占位值，现场按 panel 参数覆盖。
# ROIC 芯片寄存器 0x00 默认值。
ROIC_DEFAULT_REG_00 ?= 0
# ROIC 芯片寄存器 0x02 默认值。
ROIC_DEFAULT_REG_02 ?= 0
# ROIC 芯片寄存器 0x05 默认值。
ROIC_DEFAULT_REG_05 ?= 0
# ROIC 芯片寄存器 0x06 默认值。
ROIC_DEFAULT_REG_06 ?= 0
# ROIC 芯片寄存器 0x07 默认值。
ROIC_DEFAULT_REG_07 ?= 0
# ROIC 芯片寄存器 0x09 默认值。
ROIC_DEFAULT_REG_09 ?= 0
# ROIC 芯片寄存器 0x0A 默认值。
ROIC_DEFAULT_REG_0A ?= 0
# ROIC 芯片寄存器 0x0B 默认值。
ROIC_DEFAULT_REG_0B ?= 0
# ROIC 芯片寄存器 0x0C 默认值。
ROIC_DEFAULT_REG_0C ?= 0
# ROIC 芯片寄存器 0x0D 默认值。
ROIC_DEFAULT_REG_0D ?= 0
# ROIC 芯片寄存器 0x0E 默认值。
ROIC_DEFAULT_REG_0E ?= 0
# ROIC 芯片寄存器 0x0F 默认值。
ROIC_DEFAULT_REG_0F ?= 0
# ROIC 芯片寄存器 0x10 默认值。
ROIC_DEFAULT_REG_10 ?= 0
# ROIC 芯片寄存器 0x11 默认值。
ROIC_DEFAULT_REG_11 ?= 0
# ROIC 芯片寄存器 0x17 默认值。
ROIC_DEFAULT_REG_17 ?= 0
# ROIC 芯片寄存器 0x24 默认值。
ROIC_DEFAULT_REG_24 ?= 0
# ROIC 芯片寄存器 0x28 默认值。
ROIC_DEFAULT_REG_28 ?= 0
# ROIC 芯片寄存器 0x2D 默认值。
ROIC_DEFAULT_REG_2D ?= 0
# ROIC 芯片寄存器 0x3B 默认值。
ROIC_DEFAULT_REG_3B ?= 0

CFLAGS = -Wall -Wextra -O2 -g -std=c11 -D_GNU_SOURCE
# 生成 .d 头文件依赖，避免修改 work_mode.h/app_config.h 后增量编译漏重编相关 .c。
CFLAGS += -MMD -MP
CFLAGS += -march=$(ARCH)
CFLAGS += -DAPP_VERSION='"$(APP_VERSION)"'
CFLAGS += -DAPP_BUILD_TIME='"$(BUILD_TIME)"'
CFLAGS += -DWORK_MODE_AUTO_START=$(WORK_MODE_AUTO_START)
CFLAGS += -DWORK_MODE_DEFAULT_MODE=$(WORK_MODE_DEFAULT_MODE)
CFLAGS += -DPA_PU_BASE_ADDR=$(PA_PU_BASE_ADDR)
CFLAGS += -DPA_PU_UIO_DEVICE='"$(PA_PU_UIO_DEVICE)"'
CFLAGS += -DRS422_DEVICE='"$(RS422_DEVICE)"'
CFLAGS += -DRS422_BAUD=$(RS422_BAUD)
CFLAGS += -DDEVICE_WIDTH=$(DEVICE_WIDTH) -DDEVICE_HEIGHT=$(DEVICE_HEIGHT)
CFLAGS += -DIMAGE_WIDTH=$(IMAGE_WIDTH) -DIMAGE_HEIGHT=$(IMAGE_HEIGHT)
CFLAGS += -DCOL_OFFSET=$(COL_OFFSET) -DROW_OFFSET=$(ROW_OFFSET)
CFLAGS += -DFPGA_IMAGE_UIO_DEVICE='"$(FPGA_IMAGE_UIO_DEVICE)"'
CFLAGS += -DFPGA_OFFSET_UIO_DEVICE='"$(FPGA_OFFSET_UIO_DEVICE)"'
CFLAGS += -DFPGA_GAIN_UIO_DEVICE='"$(FPGA_GAIN_UIO_DEVICE)"'
CFLAGS += -DDDR_IMAGE_FRAME_ALIGN=$(DDR_IMAGE_FRAME_ALIGN)
CFLAGS += -DDDR_IMAGE_POOL_FRAME_COUNT=$(DDR_IMAGE_POOL_FRAME_COUNT)
CFLAGS += -DFPGA_MEM_USE_DEVMEM_FALLBACK=$(FPGA_MEM_USE_DEVMEM_FALLBACK)
CFLAGS += -DCORR_DEFAULT_PKG_NUM=$(CORR_DEFAULT_PKG_NUM)
CFLAGS += -DCORR_DEFAULT_ROW_NUM=$(CORR_DEFAULT_ROW_NUM)
CFLAGS += -DCORR_DEFAULT_COL_NUM=$(CORR_DEFAULT_COL_NUM)
CFLAGS += -DCORR_DEFAULT_OFFSET_EN=$(CORR_DEFAULT_OFFSET_EN)
CFLAGS += -DCORR_DEFAULT_OFFSET_ADDER_VALUE=$(CORR_DEFAULT_OFFSET_ADDER_VALUE)
CFLAGS += -DCORR_DEFAULT_OFFSET_CORR_MODE=$(CORR_DEFAULT_OFFSET_CORR_MODE)
CFLAGS += -DCORR_DEFAULT_GAIN_EN=$(CORR_DEFAULT_GAIN_EN)
CFLAGS += -DCORR_DEFAULT_GAIN_CLIPPING_VALUE=$(CORR_DEFAULT_GAIN_CLIPPING_VALUE)
CFLAGS += -DCORR_DEFAULT_DEFECT_EN=$(CORR_DEFAULT_DEFECT_EN)
CFLAGS += -DIMG_UPLOAD_DEFAULT_ADDR=$(IMG_UPLOAD_DEFAULT_ADDR)
CFLAGS += -DIMG_UPLOAD_DEFAULT_ROW_NUM=$(IMG_UPLOAD_DEFAULT_ROW_NUM)
CFLAGS += -DIMG_UPLOAD_DEFAULT_COL_NUM=$(IMG_UPLOAD_DEFAULT_COL_NUM)
CFLAGS += -DIMG_UPLOAD_DEFAULT_PKG_NUM=$(IMG_UPLOAD_DEFAULT_PKG_NUM)
CFLAGS += -DDYNAMIC_CYCLE_NUM=$(DYNAMIC_CYCLE_NUM)
CFLAGS += -DDYNAMIC_IMG_START_ADDR=$(DYNAMIC_IMG_START_ADDR)
CFLAGS += -DDYNAMIC_IMG_END_ADDR=$(DYNAMIC_IMG_END_ADDR)
CFLAGS += -DDYNAMIC_STEP_0_CFG_H=$(DYNAMIC_STEP_0_CFG_H)
CFLAGS += -DDYNAMIC_STEP_0_CFG_L=$(DYNAMIC_STEP_0_CFG_L)
CFLAGS += -DDYNAMIC_STEP_1_CFG_H=$(DYNAMIC_STEP_1_CFG_H) -DDYNAMIC_STEP_1_CFG_L=$(DYNAMIC_STEP_1_CFG_L)
CFLAGS += -DDYNAMIC_STEP_2_CFG_H=$(DYNAMIC_STEP_2_CFG_H) -DDYNAMIC_STEP_2_CFG_L=$(DYNAMIC_STEP_2_CFG_L)
CFLAGS += -DDYNAMIC_STEP_3_CFG_H=$(DYNAMIC_STEP_3_CFG_H) -DDYNAMIC_STEP_3_CFG_L=$(DYNAMIC_STEP_3_CFG_L)
CFLAGS += -DDYNAMIC_STEP_4_CFG_H=$(DYNAMIC_STEP_4_CFG_H) -DDYNAMIC_STEP_4_CFG_L=$(DYNAMIC_STEP_4_CFG_L)
CFLAGS += -DDYNAMIC_STEP_5_CFG_H=$(DYNAMIC_STEP_5_CFG_H) -DDYNAMIC_STEP_5_CFG_L=$(DYNAMIC_STEP_5_CFG_L)
CFLAGS += -DDYNAMIC_STEP_6_CFG_H=$(DYNAMIC_STEP_6_CFG_H) -DDYNAMIC_STEP_6_CFG_L=$(DYNAMIC_STEP_6_CFG_L)
CFLAGS += -DDYNAMIC_STEP_7_CFG_H=$(DYNAMIC_STEP_7_CFG_H) -DDYNAMIC_STEP_7_CFG_L=$(DYNAMIC_STEP_7_CFG_L)
CFLAGS += -DDYNAMIC_STEP_8_CFG_H=$(DYNAMIC_STEP_8_CFG_H) -DDYNAMIC_STEP_8_CFG_L=$(DYNAMIC_STEP_8_CFG_L)
CFLAGS += -DDYNAMIC_STEP_9_CFG_H=$(DYNAMIC_STEP_9_CFG_H) -DDYNAMIC_STEP_9_CFG_L=$(DYNAMIC_STEP_9_CFG_L)
CFLAGS += -DDYNAMIC_START_TIMEOUT_MS=$(DYNAMIC_START_TIMEOUT_MS)
CFLAGS += -DDYNAMIC_STATE_POLL_INTERVAL_MS=$(DYNAMIC_STATE_POLL_INTERVAL_MS)
CFLAGS += -DDYNAMIC_STOP_TIMEOUT_MS=$(DYNAMIC_STOP_TIMEOUT_MS)
CFLAGS += -DPA_PU_IRQ_TIMEOUT_MS=$(PA_PU_IRQ_TIMEOUT_MS)
CFLAGS += -DPA_PU_IRQ_POLL_INTERVAL_US=$(PA_PU_IRQ_POLL_INTERVAL_US)
CFLAGS += -DPA_PU_IRQ_POLL_BUSY_WAIT=$(PA_PU_IRQ_POLL_BUSY_WAIT)
CFLAGS += -DPA_PU_IRQ_POLL_BUSY_SPINS=$(PA_PU_IRQ_POLL_BUSY_SPINS)
CFLAGS += -DPA_PU_IRQ_EVENT_LOG_ENABLE=$(PA_PU_IRQ_EVENT_LOG_ENABLE)
CFLAGS += -DPA_IRQ_DEVICE='"$(PA_IRQ_DEVICE)"'
CFLAGS += -DSTATIC_IDLE_CLEAN_INTERVAL_MS=$(STATIC_IDLE_CLEAN_INTERVAL_MS)
CFLAGS += -DSTATIC_IDLE_CLEAN_LOG_ENABLE=$(STATIC_IDLE_CLEAN_LOG_ENABLE)
CFLAGS += -DSTATIC_IDLE_EXPOSURE_MS=$(STATIC_IDLE_EXPOSURE_MS)
CFLAGS += -DSTATIC_IDLE_DARK_WINDOW_MS=$(STATIC_IDLE_DARK_WINDOW_MS)
CFLAGS += -DTEMPLATE_OFFSET_FILE='"$(TEMPLATE_OFFSET_FILE)"'
CFLAGS += -DTEMPLATE_GAIN_FILE='"$(TEMPLATE_GAIN_FILE)"'
CFLAGS += -DCAL_GAIN_DIR='"$(CAL_GAIN_DIR)"'
CFLAGS += -DGAIN_TASK_BACKGROUND_ENABLE=$(GAIN_TASK_BACKGROUND_ENABLE)
CFLAGS += -DGIC_DEFAULT_REQ_CODE=$(GIC_DEFAULT_REQ_CODE)
CFLAGS += -DGIC_DEFAULT_DOUT_EN=$(GIC_DEFAULT_DOUT_EN)
CFLAGS += -DGIC_DEFAULT_LINE_TIME_NS=$(GIC_DEFAULT_LINE_TIME_NS)
CFLAGS += -DGIC_DEFAULT_OE_RISE_NS=$(GIC_DEFAULT_OE_RISE_NS)
CFLAGS += -DGIC_DEFAULT_OE_FALL_NS=$(GIC_DEFAULT_OE_FALL_NS)
CFLAGS += -DGIC_DEFAULT_START_ROW=$(GIC_DEFAULT_START_ROW)
CFLAGS += -DGIC_DEFAULT_END_ROW=$(GIC_DEFAULT_END_ROW)
CFLAGS += -DGIC_DEFAULT_BINNING=$(GIC_DEFAULT_BINNING)
CFLAGS += -DROIC_DEFAULT_START_COL=$(ROIC_DEFAULT_START_COL)
CFLAGS += -DROIC_DEFAULT_END_COL=$(ROIC_DEFAULT_END_COL)
CFLAGS += -DROIC_DEFAULT_BINNING=$(ROIC_DEFAULT_BINNING)
CFLAGS += -DROIC_DEFAULT_REG_00=$(ROIC_DEFAULT_REG_00)
CFLAGS += -DROIC_DEFAULT_REG_02=$(ROIC_DEFAULT_REG_02)
CFLAGS += -DROIC_DEFAULT_REG_05=$(ROIC_DEFAULT_REG_05)
CFLAGS += -DROIC_DEFAULT_REG_06=$(ROIC_DEFAULT_REG_06)
CFLAGS += -DROIC_DEFAULT_REG_07=$(ROIC_DEFAULT_REG_07)
CFLAGS += -DROIC_DEFAULT_REG_09=$(ROIC_DEFAULT_REG_09)
CFLAGS += -DROIC_DEFAULT_REG_0A=$(ROIC_DEFAULT_REG_0A)
CFLAGS += -DROIC_DEFAULT_REG_0B=$(ROIC_DEFAULT_REG_0B)
CFLAGS += -DROIC_DEFAULT_REG_0C=$(ROIC_DEFAULT_REG_0C)
CFLAGS += -DROIC_DEFAULT_REG_0D=$(ROIC_DEFAULT_REG_0D)
CFLAGS += -DROIC_DEFAULT_REG_0E=$(ROIC_DEFAULT_REG_0E)
CFLAGS += -DROIC_DEFAULT_REG_0F=$(ROIC_DEFAULT_REG_0F)
CFLAGS += -DROIC_DEFAULT_REG_10=$(ROIC_DEFAULT_REG_10)
CFLAGS += -DROIC_DEFAULT_REG_11=$(ROIC_DEFAULT_REG_11)
CFLAGS += -DROIC_DEFAULT_REG_17=$(ROIC_DEFAULT_REG_17)
CFLAGS += -DROIC_DEFAULT_REG_24=$(ROIC_DEFAULT_REG_24)
CFLAGS += -DROIC_DEFAULT_REG_28=$(ROIC_DEFAULT_REG_28)
CFLAGS += -DROIC_DEFAULT_REG_2D=$(ROIC_DEFAULT_REG_2D)
CFLAGS += -DROIC_DEFAULT_REG_3B=$(ROIC_DEFAULT_REG_3B)
LDFLAGS = -lpthread

SRCS = src/main.c \
       src/auto_offset_plan.c \
       src/log.c \
       src/fpga_mem.c \
       src/pa_pu.c \
       src/dynamic_mode.c \
       src/work_mode.c \
       src/rs422.c \
       src/template_builder.c \
       src/calibration_builder.c \
       src/command_handler.c

OBJS = $(SRCS:%.c=$(BUILD_DIR)/%.o)
DEPS = $(OBJS:.o=.d)

all: $(BIN_DIR)/$(TARGET)

$(BIN_DIR):
	mkdir -p $@

$(BUILD_DIR)/%.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BIN_DIR)/$(TARGET): $(OBJS) | $(BIN_DIR)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LDFLAGS)

deploy: $(BIN_DIR)/$(TARGET)
	$(STRIP) $(BIN_DIR)/$(TARGET) -o $(BIN_DIR)/$(TARGET)_deploy

deploy-board: $(BIN_DIR)/$(TARGET)
	$(SSHPASS) scp -o StrictHostKeyChecking=no $(BIN_DIR)/$(TARGET) $(BOARD_USER)@$(BOARD_HOST):$(BOARD_DIR)/$(TARGET)
	$(SSHPASS) ssh -o StrictHostKeyChecking=no $(BOARD_USER)@$(BOARD_HOST) "chmod +x $(BOARD_DIR)/$(TARGET)"

run-board: deploy-board
	$(SSHPASS) ssh -o StrictHostKeyChecking=no $(BOARD_USER)@$(BOARD_HOST) "$(BOARD_DIR)/$(TARGET) $(BOARD_RUN_ARGS)"

config:
	@echo "CC = $(CC)"
	@echo "STRIP = $(STRIP)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "LDFLAGS = $(LDFLAGS)"
	@echo "BOARD = $(BOARD_USER)@$(BOARD_HOST):$(BOARD_DIR)"
	@echo "BOARD_PASS = $(BOARD_PASS)"
	@echo "BOARD_RUN_ARGS = $(BOARD_RUN_ARGS)"
	@echo "APP_VERSION = $(APP_VERSION)"
	@echo "BUILD_TIME = $(BUILD_TIME)"
	@echo "WORK_MODE = auto_start=$(WORK_MODE_AUTO_START) default_mode=$(WORK_MODE_DEFAULT_MODE)"
	@echo "DYNAMIC = cycle=$(DYNAMIC_CYCLE_NUM) img_start=$(DYNAMIC_IMG_START_ADDR) img_end=$(DYNAMIC_IMG_END_ADDR) step0_h=$(DYNAMIC_STEP_0_CFG_H) step0_l=$(DYNAMIC_STEP_0_CFG_L) start_timeout_ms=$(DYNAMIC_START_TIMEOUT_MS) poll_ms=$(DYNAMIC_STATE_POLL_INTERVAL_MS) stop_timeout_ms=$(DYNAMIC_STOP_TIMEOUT_MS)"
	@echo "DYNAMIC_STEPS_1_3 = 1:$(DYNAMIC_STEP_1_CFG_H)/$(DYNAMIC_STEP_1_CFG_L) 2:$(DYNAMIC_STEP_2_CFG_H)/$(DYNAMIC_STEP_2_CFG_L) 3:$(DYNAMIC_STEP_3_CFG_H)/$(DYNAMIC_STEP_3_CFG_L)"
	@echo "DYNAMIC_STEPS_4_6 = 4:$(DYNAMIC_STEP_4_CFG_H)/$(DYNAMIC_STEP_4_CFG_L) 5:$(DYNAMIC_STEP_5_CFG_H)/$(DYNAMIC_STEP_5_CFG_L) 6:$(DYNAMIC_STEP_6_CFG_H)/$(DYNAMIC_STEP_6_CFG_L)"
	@echo "DYNAMIC_STEPS_7_9 = 7:$(DYNAMIC_STEP_7_CFG_H)/$(DYNAMIC_STEP_7_CFG_L) 8:$(DYNAMIC_STEP_8_CFG_H)/$(DYNAMIC_STEP_8_CFG_L) 9:$(DYNAMIC_STEP_9_CFG_H)/$(DYNAMIC_STEP_9_CFG_L)"
	@echo "PA_PU_IRQ_EVENT_LOG_ENABLE = $(PA_PU_IRQ_EVENT_LOG_ENABLE)"
	@echo "PA_PU_BASE_ADDR = $(PA_PU_BASE_ADDR)"
	@echo "PA_PU_UIO_DEVICE = $(PA_PU_UIO_DEVICE)"
	@echo "RS422_DEVICE = $(RS422_DEVICE)"
	@echo "RS422_BAUD = $(RS422_BAUD)"
	@echo "DEVICE = $(DEVICE_WIDTH)x$(DEVICE_HEIGHT)"
	@echo "IMAGE = $(IMAGE_WIDTH)x$(IMAGE_HEIGHT)"
	@echo "OFFSET = ($(COL_OFFSET),$(ROW_OFFSET))"
	@echo "FPGA_IMAGE = uio=$(FPGA_IMAGE_UIO_DEVICE) phys/size=read-from-uio-map0"
	@echo "FPGA_OFFSET = uio=$(FPGA_OFFSET_UIO_DEVICE) phys/size=read-from-uio-map0"
	@echo "FPGA_GAIN = uio=$(FPGA_GAIN_UIO_DEVICE) phys/size=read-from-uio-map0"
	@echo "DDR_IMAGE_POOL = uio=$(FPGA_IMAGE_UIO_DEVICE) frame_align=$(DDR_IMAGE_FRAME_ALIGN) frame_count=$(DDR_IMAGE_POOL_FRAME_COUNT)"
	@echo "CORR = pkg=$(CORR_DEFAULT_PKG_NUM) image=$(CORR_DEFAULT_COL_NUM)x$(CORR_DEFAULT_ROW_NUM) offset_en=$(CORR_DEFAULT_OFFSET_EN) offset_adder=$(CORR_DEFAULT_OFFSET_ADDER_VALUE) offset_mode=$(CORR_DEFAULT_OFFSET_CORR_MODE) gain_en=$(CORR_DEFAULT_GAIN_EN) gain_clip=$(CORR_DEFAULT_GAIN_CLIPPING_VALUE) defect_en=$(CORR_DEFAULT_DEFECT_EN)"
	@echo "IRQ = timeout_ms=$(PA_PU_IRQ_TIMEOUT_MS) poll_interval_us=$(PA_PU_IRQ_POLL_INTERVAL_US)"
	@echo "IRQ_POLL = busy_wait=$(PA_PU_IRQ_POLL_BUSY_WAIT) busy_spins=$(PA_PU_IRQ_POLL_BUSY_SPINS)"
	@echo "PA_IRQ_DEVICE = $(PA_IRQ_DEVICE)"
	@echo "STATIC_IDLE = clean_ms=$(STATIC_IDLE_CLEAN_INTERVAL_MS) exposure_ms=$(STATIC_IDLE_EXPOSURE_MS) dark_window_ms=$(STATIC_IDLE_DARK_WINDOW_MS)"
	@echo "GIC = req=$(GIC_DEFAULT_REQ_CODE) dout=$(GIC_DEFAULT_DOUT_EN) line_time_ns=$(GIC_DEFAULT_LINE_TIME_NS) oe_rise_ns=$(GIC_DEFAULT_OE_RISE_NS) oe_fall_ns=$(GIC_DEFAULT_OE_FALL_NS) rows=$(GIC_DEFAULT_START_ROW)-$(GIC_DEFAULT_END_ROW) binning=$(GIC_DEFAULT_BINNING)"
	@echo "ROIC = cols=$(ROIC_DEFAULT_START_COL)-$(ROIC_DEFAULT_END_COL) binning=$(ROIC_DEFAULT_BINNING)"

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all clean config deploy deploy-board run-board

-include $(DEPS)
