# Makefile for PA controller application

TOOLCHAIN_DIR ?= /home/zhe/sdk/kosmo2/pango_config/misc/toolchain/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu/bin
CROSS_COMPILE ?= $(TOOLCHAIN_DIR)/aarch64-linux-gnu-
ifeq ($(origin CC),default)
CC = $(CROSS_COMPILE)gcc
endif
STRIP ?= $(CROSS_COMPILE)strip

# 输出目标与构建目录。
TARGET = pa_controller
BUILD_DIR = build
BIN_DIR = $(BUILD_DIR)/bin

# 本应用软件版本号，启动日志和 VERSION 命令会显示。
APP_VERSION ?= 0.1.0

# 开发板部署/运行参数，deploy-board 和 run-board 目标使用。
BOARD_HOST ?= 192.168.3.17
BOARD_USER ?= root
BOARD_PASS ?= root
BOARD_DIR ?= /root
BOARD_RUN_ARGS ?= -d $(RS422_DEVICE) -b $(RS422_BAUD)
SSHPASS ?= sshpass -p $(BOARD_PASS)

# 编译架构和 PA/PU AXI-lite 寄存器访问入口。
ARCH ?= armv8-a
PA_PU_BASE_ADDR ?= 0x40000000
PA_PU_UIO_DEVICE ?=

# 上位机通讯串口配置。
RS422_DEVICE ?= /dev/ttyS1
RS422_BAUD ?= 115200

# FPGA 写入 DDR 的整幅图尺寸，以及应用实际处理的有效图像尺寸。
DEVICE_WIDTH ?= 3072
DEVICE_HEIGHT ?= 7680
IMAGE_WIDTH ?= 3072
IMAGE_HEIGHT ?= 7680

# 有效图像在整幅 FPGA 图像中的起始偏移。
COL_OFFSET ?= 0
ROW_OFFSET ?= 0

# 三块共享 DDR 物理地址：原始图、暗场 offset 模板、亮场 gain 模板。
FPGA_IMAGE_PTR ?= 0x28000000
FPGA_OFFSET_PTR ?= 0x3C000000
FPGA_GAIN_PTR ?= 0x38000000

# 三块共享 DDR 对应的 UIO 设备节点。
FPGA_IMAGE_UIO_DEVICE ?= /dev/uio2
FPGA_OFFSET_UIO_DEVICE ?= /dev/uio0
FPGA_GAIN_UIO_DEVICE ?= /dev/uio1

# 三块共享 DDR 的映射窗口大小。
FPGA_IMAGE_UIO_SIZE ?= 0x10000000
FPGA_OFFSET_UIO_SIZE ?= 0x04000000
FPGA_GAIN_UIO_SIZE ?= 0x04000000

# UIO 打开失败时是否允许回退 /dev/mem，默认关闭。
FPGA_MEM_USE_DEVMEM_FALLBACK ?= 0

# gain 模板在亮场 DDR 窗口中重复写入的份数。
GAIN_TEMPLATE_REPEAT_COUNT ?= 1

# CONFIG_CORR 不带参数时使用的图像校正默认配置。
# img_pkg_num = 行 * 列 * 2 / 1024，默认 7680x3072x16bit 图像为 46080 包。
CORR_DEFAULT_ROW_NUM ?= 7680
CORR_DEFAULT_COL_NUM ?= 3072
CORR_DEFAULT_PKG_NUM ?= $(shell expr $(CORR_DEFAULT_ROW_NUM) \* $(CORR_DEFAULT_COL_NUM) \* 2 / 1024)
CORR_DEFAULT_OFFSET_EN ?= 1
CORR_DEFAULT_OFFSET_ADDR ?= $(FPGA_OFFSET_PTR)
CORR_DEFAULT_OFFSET_ADDER_VALUE ?= 100
CORR_DEFAULT_GAIN_EN ?= 1
CORR_DEFAULT_GAIN_ADDR ?= $(FPGA_GAIN_PTR)
CORR_DEFAULT_GAIN_CLIPPING_VALUE ?= 55000
CORR_DEFAULT_DEFECT_EN ?= 0

# START_GIC/START_ROIC/START_CORR/SEND_SINGLE 等命令等待中断的参数。
PA_PU_IRQ_TIMEOUT_MS ?= 5000
PA_PU_IRQ_POLL_INTERVAL_US ?= 1000
PA_IRQ_DEVICE ?= /dev/pa_irq

# CONFIG_GIC 不带参数时使用的 GIC 时序和行范围默认配置。
GIC_DEFAULT_REQ_CODE ?= 0
GIC_DEFAULT_DOUT_EN ?= 1
GIC_DEFAULT_LINE_TIME_NS ?= 0
GIC_DEFAULT_OE_RISE_NS ?= 0
GIC_DEFAULT_OE_FALL_NS ?= 0
GIC_DEFAULT_START_ROW ?= 0
GIC_DEFAULT_END_ROW ?= $(shell expr $(IMAGE_HEIGHT) - 1)
GIC_DEFAULT_BINNING ?= 1

# CONFIG_ROIC 不带参数时使用的列范围和 binning 默认配置。
ROIC_DEFAULT_START_COL ?= 0
ROIC_DEFAULT_END_COL ?= $(shell expr $(IMAGE_WIDTH) - 1)
ROIC_DEFAULT_BINNING ?= 1

# CONFIG_ROIC 下发的 ROIC 芯片寄存器默认值，当前为占位值，现场按 panel 参数覆盖。
ROIC_DEFAULT_REG_00 ?= 0
ROIC_DEFAULT_REG_02 ?= 0
ROIC_DEFAULT_REG_05 ?= 0
ROIC_DEFAULT_REG_06 ?= 0
ROIC_DEFAULT_REG_07 ?= 0
ROIC_DEFAULT_REG_09 ?= 0
ROIC_DEFAULT_REG_0A ?= 0
ROIC_DEFAULT_REG_0B ?= 0
ROIC_DEFAULT_REG_0C ?= 0
ROIC_DEFAULT_REG_0D ?= 0
ROIC_DEFAULT_REG_0E ?= 0
ROIC_DEFAULT_REG_0F ?= 0
ROIC_DEFAULT_REG_10 ?= 0
ROIC_DEFAULT_REG_11 ?= 0
ROIC_DEFAULT_REG_17 ?= 0
ROIC_DEFAULT_REG_24 ?= 0
ROIC_DEFAULT_REG_28 ?= 0
ROIC_DEFAULT_REG_2D ?= 0
ROIC_DEFAULT_REG_3B ?= 0

CFLAGS = -Wall -Wextra -O2 -g -std=c11 -D_GNU_SOURCE
CFLAGS += -march=$(ARCH)
CFLAGS += -DAPP_VERSION='"$(APP_VERSION)"'
CFLAGS += -DPA_PU_BASE_ADDR=$(PA_PU_BASE_ADDR)
CFLAGS += -DPA_PU_UIO_DEVICE='"$(PA_PU_UIO_DEVICE)"'
CFLAGS += -DRS422_DEVICE='"$(RS422_DEVICE)"'
CFLAGS += -DRS422_BAUD=$(RS422_BAUD)
CFLAGS += -DDEVICE_WIDTH=$(DEVICE_WIDTH) -DDEVICE_HEIGHT=$(DEVICE_HEIGHT)
CFLAGS += -DIMAGE_WIDTH=$(IMAGE_WIDTH) -DIMAGE_HEIGHT=$(IMAGE_HEIGHT)
CFLAGS += -DCOL_OFFSET=$(COL_OFFSET) -DROW_OFFSET=$(ROW_OFFSET)
CFLAGS += -DFPGA_IMAGE_PTR=$(FPGA_IMAGE_PTR)
CFLAGS += -DFPGA_OFFSET_PTR=$(FPGA_OFFSET_PTR)
CFLAGS += -DFPGA_GAIN_PTR=$(FPGA_GAIN_PTR)
CFLAGS += -DFPGA_IMAGE_UIO_DEVICE='"$(FPGA_IMAGE_UIO_DEVICE)"'
CFLAGS += -DFPGA_OFFSET_UIO_DEVICE='"$(FPGA_OFFSET_UIO_DEVICE)"'
CFLAGS += -DFPGA_GAIN_UIO_DEVICE='"$(FPGA_GAIN_UIO_DEVICE)"'
CFLAGS += -DFPGA_IMAGE_UIO_SIZE=$(FPGA_IMAGE_UIO_SIZE)
CFLAGS += -DFPGA_OFFSET_UIO_SIZE=$(FPGA_OFFSET_UIO_SIZE)
CFLAGS += -DFPGA_GAIN_UIO_SIZE=$(FPGA_GAIN_UIO_SIZE)
CFLAGS += -DFPGA_MEM_USE_DEVMEM_FALLBACK=$(FPGA_MEM_USE_DEVMEM_FALLBACK)
CFLAGS += -DGAIN_TEMPLATE_REPEAT_COUNT=$(GAIN_TEMPLATE_REPEAT_COUNT)
CFLAGS += -DCORR_DEFAULT_PKG_NUM=$(CORR_DEFAULT_PKG_NUM)
CFLAGS += -DCORR_DEFAULT_ROW_NUM=$(CORR_DEFAULT_ROW_NUM)
CFLAGS += -DCORR_DEFAULT_COL_NUM=$(CORR_DEFAULT_COL_NUM)
CFLAGS += -DCORR_DEFAULT_OFFSET_EN=$(CORR_DEFAULT_OFFSET_EN)
CFLAGS += -DCORR_DEFAULT_OFFSET_ADDR=$(CORR_DEFAULT_OFFSET_ADDR)
CFLAGS += -DCORR_DEFAULT_OFFSET_ADDER_VALUE=$(CORR_DEFAULT_OFFSET_ADDER_VALUE)
CFLAGS += -DCORR_DEFAULT_GAIN_EN=$(CORR_DEFAULT_GAIN_EN)
CFLAGS += -DCORR_DEFAULT_GAIN_ADDR=$(CORR_DEFAULT_GAIN_ADDR)
CFLAGS += -DCORR_DEFAULT_GAIN_CLIPPING_VALUE=$(CORR_DEFAULT_GAIN_CLIPPING_VALUE)
CFLAGS += -DCORR_DEFAULT_DEFECT_EN=$(CORR_DEFAULT_DEFECT_EN)
CFLAGS += -DPA_PU_IRQ_TIMEOUT_MS=$(PA_PU_IRQ_TIMEOUT_MS)
CFLAGS += -DPA_PU_IRQ_POLL_INTERVAL_US=$(PA_PU_IRQ_POLL_INTERVAL_US)
CFLAGS += -DPA_IRQ_DEVICE='"$(PA_IRQ_DEVICE)"'
CFLAGS += -DGIC_DEFAULT_REQ_CODE=$(GIC_DEFAULT_REQ_CODE)
CFLAGS += -DGIC_DEFAULT_DOUT_EN=$(GIC_DEFAULT_DOUT_EN)
CFLAGS += -DGIC_DEFAULT_LINE_TIME_NS=$(GIC_DEFAULT_LINE_TIME_NS)
CFLAGS += -DGIC_DEFAULT_OE_RISE_NS=$(GIC_DEFAULT_OE_RISE_NS)
CFLAGS += -DGIC_DEFAULT_OE_FALL_NS=$(GIC_DEFAULT_OE_FALL_NS)
CFLAGS += -DGIC_DEFAULT_START_ROW=$(GIC_DEFAULT_START_ROW)
CFLAGS += -DGIC_DEFAULT_END_ROW=$(GIC_DEFAULT_END_ROW)
CFLAGS += -DGIC_DEFAULT_BINNING=$(GIC_DEFAULT_BINNING)
CFLAGS += -DROIC_DEFAULT_START_COL=$(ROIC_DEFAULT_START_COL)
CFLAGS += -DROIC_DEFAULT_END_COL=$(ROIC_DEFAULT_END_COL)
CFLAGS += -DROIC_DEFAULT_BINNING=$(ROIC_DEFAULT_BINNING)
CFLAGS += -DROIC_DEFAULT_REG_00=$(ROIC_DEFAULT_REG_00)
CFLAGS += -DROIC_DEFAULT_REG_02=$(ROIC_DEFAULT_REG_02)
CFLAGS += -DROIC_DEFAULT_REG_05=$(ROIC_DEFAULT_REG_05)
CFLAGS += -DROIC_DEFAULT_REG_06=$(ROIC_DEFAULT_REG_06)
CFLAGS += -DROIC_DEFAULT_REG_07=$(ROIC_DEFAULT_REG_07)
CFLAGS += -DROIC_DEFAULT_REG_09=$(ROIC_DEFAULT_REG_09)
CFLAGS += -DROIC_DEFAULT_REG_0A=$(ROIC_DEFAULT_REG_0A)
CFLAGS += -DROIC_DEFAULT_REG_0B=$(ROIC_DEFAULT_REG_0B)
CFLAGS += -DROIC_DEFAULT_REG_0C=$(ROIC_DEFAULT_REG_0C)
CFLAGS += -DROIC_DEFAULT_REG_0D=$(ROIC_DEFAULT_REG_0D)
CFLAGS += -DROIC_DEFAULT_REG_0E=$(ROIC_DEFAULT_REG_0E)
CFLAGS += -DROIC_DEFAULT_REG_0F=$(ROIC_DEFAULT_REG_0F)
CFLAGS += -DROIC_DEFAULT_REG_10=$(ROIC_DEFAULT_REG_10)
CFLAGS += -DROIC_DEFAULT_REG_11=$(ROIC_DEFAULT_REG_11)
CFLAGS += -DROIC_DEFAULT_REG_17=$(ROIC_DEFAULT_REG_17)
CFLAGS += -DROIC_DEFAULT_REG_24=$(ROIC_DEFAULT_REG_24)
CFLAGS += -DROIC_DEFAULT_REG_28=$(ROIC_DEFAULT_REG_28)
CFLAGS += -DROIC_DEFAULT_REG_2D=$(ROIC_DEFAULT_REG_2D)
CFLAGS += -DROIC_DEFAULT_REG_3B=$(ROIC_DEFAULT_REG_3B)
LDFLAGS = -lpthread

SRCS = src/main.c \
       src/auto_offset_plan.c \
       src/log.c \
       src/fpga_mem.c \
       src/pa_pu.c \
       src/rs422.c \
       src/template_builder.c \
       src/command_handler.c

OBJS = $(SRCS:%.c=$(BUILD_DIR)/%.o)

all: $(BIN_DIR)/$(TARGET)

$(BIN_DIR):
	mkdir -p $@

$(BUILD_DIR)/%.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BIN_DIR)/$(TARGET): $(OBJS) | $(BIN_DIR)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LDFLAGS)

deploy: $(BIN_DIR)/$(TARGET)
	$(STRIP) $(BIN_DIR)/$(TARGET) -o $(BIN_DIR)/$(TARGET)_deploy

deploy-board: $(BIN_DIR)/$(TARGET)
	$(SSHPASS) scp -o StrictHostKeyChecking=no $(BIN_DIR)/$(TARGET) $(BOARD_USER)@$(BOARD_HOST):$(BOARD_DIR)/$(TARGET)
	$(SSHPASS) ssh -o StrictHostKeyChecking=no $(BOARD_USER)@$(BOARD_HOST) "chmod +x $(BOARD_DIR)/$(TARGET)"

run-board: deploy-board
	$(SSHPASS) ssh -o StrictHostKeyChecking=no $(BOARD_USER)@$(BOARD_HOST) "$(BOARD_DIR)/$(TARGET) $(BOARD_RUN_ARGS)"

config:
	@echo "CC = $(CC)"
	@echo "STRIP = $(STRIP)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "LDFLAGS = $(LDFLAGS)"
	@echo "BOARD = $(BOARD_USER)@$(BOARD_HOST):$(BOARD_DIR)"
	@echo "BOARD_PASS = $(BOARD_PASS)"
	@echo "BOARD_RUN_ARGS = $(BOARD_RUN_ARGS)"
	@echo "APP_VERSION = $(APP_VERSION)"
	@echo "PA_PU_BASE_ADDR = $(PA_PU_BASE_ADDR)"
	@echo "PA_PU_UIO_DEVICE = $(PA_PU_UIO_DEVICE)"
	@echo "RS422_DEVICE = $(RS422_DEVICE)"
	@echo "RS422_BAUD = $(RS422_BAUD)"
	@echo "DEVICE = $(DEVICE_WIDTH)x$(DEVICE_HEIGHT)"
	@echo "IMAGE = $(IMAGE_WIDTH)x$(IMAGE_HEIGHT)"
	@echo "OFFSET = ($(COL_OFFSET),$(ROW_OFFSET))"
	@echo "FPGA_IMAGE = ptr=$(FPGA_IMAGE_PTR) uio=$(FPGA_IMAGE_UIO_DEVICE) size=$(FPGA_IMAGE_UIO_SIZE)"
	@echo "FPGA_OFFSET = ptr=$(FPGA_OFFSET_PTR) uio=$(FPGA_OFFSET_UIO_DEVICE) size=$(FPGA_OFFSET_UIO_SIZE)"
	@echo "FPGA_GAIN = ptr=$(FPGA_GAIN_PTR) uio=$(FPGA_GAIN_UIO_DEVICE) size=$(FPGA_GAIN_UIO_SIZE) repeat=$(GAIN_TEMPLATE_REPEAT_COUNT)"
	@echo "CORR = pkg=$(CORR_DEFAULT_PKG_NUM) image=$(CORR_DEFAULT_COL_NUM)x$(CORR_DEFAULT_ROW_NUM) offset_en=$(CORR_DEFAULT_OFFSET_EN) offset_addr=$(CORR_DEFAULT_OFFSET_ADDR) offset_adder=$(CORR_DEFAULT_OFFSET_ADDER_VALUE) gain_en=$(CORR_DEFAULT_GAIN_EN) gain_addr=$(CORR_DEFAULT_GAIN_ADDR) gain_clip=$(CORR_DEFAULT_GAIN_CLIPPING_VALUE) defect_en=$(CORR_DEFAULT_DEFECT_EN)"
	@echo "IRQ = timeout_ms=$(PA_PU_IRQ_TIMEOUT_MS) poll_interval_us=$(PA_PU_IRQ_POLL_INTERVAL_US)"
	@echo "PA_IRQ_DEVICE = $(PA_IRQ_DEVICE)"
	@echo "GIC = req=$(GIC_DEFAULT_REQ_CODE) dout=$(GIC_DEFAULT_DOUT_EN) line_time_ns=$(GIC_DEFAULT_LINE_TIME_NS) oe_rise_ns=$(GIC_DEFAULT_OE_RISE_NS) oe_fall_ns=$(GIC_DEFAULT_OE_FALL_NS) rows=$(GIC_DEFAULT_START_ROW)-$(GIC_DEFAULT_END_ROW) binning=$(GIC_DEFAULT_BINNING)"
	@echo "ROIC = cols=$(ROIC_DEFAULT_START_COL)-$(ROIC_DEFAULT_END_COL) binning=$(ROIC_DEFAULT_BINNING)"

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all clean config deploy deploy-board run-board
